name: 'PR Media Notifier'
description: 'Easily share PR medias on a Slack channel'
author: 'Donovan Fournier'
inputs:
  milliseconds: # change this
    required: true
    description: 'input description here'
    default: 'default value if applicable'
runs:
  using: 'node16'
  main: 'dist/index.js'
