name: 'PR Media Notifier'
description: 'Easily share PR medias on a Slack channel'
author: 'Donovan Fournier'
inputs:
  text-input:
    required: true
    description: 'This is an example text input'
runs:
  using: 'node16'
  main: 'dist/index.js'
