name: 'local-test'
on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          slack-token: ${{ secrets.SLACK_APP_KEY }}
          slack-channel: ${{ secrets.SLACK_CHANNEL_ID }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
